#!/usr/bin/env sh
set -eu

if [ "$#" -ne 3 ]; then
	echo "Usage: $0 <input.bin> <output.c> <symbol>" >&2
	exit 1
fi

input="$1"
output="$2"
symbol="$3"

if [ ! -s "$input" ]; then
	echo "bin2c-fallback: input is missing or empty: $input" >&2
	exit 1
fi

size="$(wc -c < "$input" | tr -d '[:space:]')"
tmp="${output}.tmp"

{
	echo "/* Auto-generated by scripts/bin2c-fallback.sh */"
	echo "#include <tamtypes.h>"
	echo ""
	echo "u8 ${symbol}[] __attribute__((aligned(16))) = {"

	od -An -v -tx1 "$input" | awk '
		NF {
			printf "\t";
			for (i = 1; i <= NF; ++i) {
				printf "0x%s,", $i;
				if (i < NF) {
					printf " ";
				}
			}
			printf "\n";
		}
	'

	echo "};"
	echo "int size_${symbol} = ${size};"
} > "$tmp"

mv "$tmp" "$output"
