#!/usr/bin/env sh
set -eu

if [ "$#" -ne 3 ]; then
	echo "Usage: $0 <input.bin> <output.s> <symbol>" >&2
	exit 1
fi

input="$1"
output="$2"
symbol="$3"

size="$(wc -c < "$input" | tr -d '[:space:]')"
tmp="${output}.tmp"

{
	echo "/* Auto-generated by scripts/bin2s-fallback.sh */"
	echo "    .section .rodata"
	echo "    .align 4"
	echo "    .global ${symbol}"
	echo "    .global size_${symbol}"
	echo "${symbol}:"

	od -An -v -tx1 "$input" | awk '
		NF {
			printf "    .byte ";
			for (i = 1; i <= NF; ++i) {
				printf "%s0x%s", (i == 1 ? "" : ", "), $i;
			}
			printf "\n";
		}
	'

	echo "    .align 2"
	echo "size_${symbol}:"
	echo "    .word ${size}"
} > "$tmp"

mv "$tmp" "$output"
